### ISSUE TITLE
Normalization parameters on preprocessing

### ISSUE THREAD

**Issue by j-oflaherty** [hellomuffin/exif-as-language#9]
Hi,

Thanks for sharing the code. We were looking at it and found the normalization parameters of the preprocessing are hardcoded. We would like to know how this values were chosen / found.

Thank you,
Julian

**Comment by hellomuffin** [comment]
Hi,
We follow the normalization parameter at OpenAI CLIP code.

**Comment by j-oflaherty** [comment]
Thanks
